blog/urls.py
from unicodedata import name
from django.urls import path,include
from blog.views import *

app_name='blog'

urlpatterns = [
    path('',home,name="index"),
    path('blog-grid',blog_gird,name="blog-grid"),
    path('blog-single',blog_single,name="blog-single"),
    path('blog-single/<int:pid>',blog_single,name="blog-single"),
]

dbtest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from email.policy import default
from pickle import FALSE
from django.db import models

# Create your models here.
class Post(models.Model):
    category = models.CharField(max_length=255)
    picture = models.ImageField(max_length=255,default='statics/assets/img/post-1.jpg')
    title = models.CharField(max_length=255)
    about_title = models.CharField(max_length=255)
    published_date = models.DateField()
    created_date = models.DateField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)
    author = models.CharField(max_length=255)
    content = models.TextField()
    quote_content = models.TextField()
    quote_author = models.CharField(max_length=255)
    status = models.BooleanField(default=True)
    counted_views = models.PositiveIntegerField(default=0)



    def __str__(self):
        return self.title+str(self.id)

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post
from datetime import datetime
from django.db.models import F

# Create your views here.
def home(request):
    return render(request,'index.html')

def blog_gird(request):
    posts = Post.objects.filter(published_date__lte=datetime.now())
    context = {'posts': posts}
    return render(request,'blog-grid.html',context)


def blog_single(request):
    # post = get_object_or_404(Post, pk=pid)
    
    # context = {'post': post}
    return render(request,'blog-single.html')

templates/blog-grid.html
{% extends "base.html" %}{% load static %}{% block content %}{% load tags %}

<main id="main">

    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <div class="title-single-box">
                        <h1 class="title-single">Our Amazing Posts</h1>
                        <span class="color-text-a">Grid News</span>
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{% url 'blog:index' %}">Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                News Grid
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Intro Single-->

    <!-- =======  Blog Grid ======= -->
    <section class="news-grid grid">
        <div class="container">
            <div class="row">
                {% for post in posts %}
                <div class="col-md-4">
                    <div class="card-box-b card-shadow news-box">
                        <div class="img-box-b">
                            <img src="{{post.picture.url}}" alt="" class="img-b img-fluid">
                        </div>
                        <div class="card-overlay">
                            <div class="card-header-b">
                                <div class="card-category-b">
                                    <a href="#" class="category-b">{{ post.category }}</a>
                                </div>
                                <div class="card-title-b">
                                    <h2 class="title-2">
                                        <a href="{% url 'blog:blog-single' pid=post.id %}">{{ post.title }}
                        <br> {{ post.about_title }}</a>
                                    </h2>
                                    <!-- <p>{{post.content|truncatewords:5}}</p> -->
                                    <p>{{post.content|shorter}}</p>
                                </div>
                                <div class="card-date">
                                    <span class="date-b">{{ post.published_date }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <nav class="pagination-a">
                        <ul class="pagination justify-content-end">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">
                                    <span class="bi bi-chevron-left"></span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">1</a>
                            </li>
                            <li class="page-item active">
                                <a class="page-link" href="#">2</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="#">3</a>
                            </li>
                            <li class="page-item next">
                                <a class="page-link" href="#">
                                    <span class="bi bi-chevron-right"></span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Blog Grid-->

</main>
<!-- End #main -->
{% endblock %}

templates/blog-single.html
{% extends "base.html" %}{% load static %}{% block content %}

<main id="main">

    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <div class="title-single-box">
                        <h1 class="title-single">{{ post.title }}</h1>
                        <span class="color-text-a">{{post.about_title}}</span>
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Book Cover Deisgn
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Intro Single-->

    <!-- ======= Blog Single ======= -->
    <section class="news-single nav-arrow-b">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="news-img-box">
                        <img src="{% static 'assets/img/slide-' %}{{post.id}}.jpg" alt="" alt="" class="img-fluid">
                    </div>
                </div>
                <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
                    <div class="post-information">
                        <ul class="list-inline text-center color-a">
                            <li class="list-inline-item mr-2">
                                <strong>Author: </strong>
                                <span class="color-text-a">{{post.author}}</span>
                            </li>
                            <li class="list-inline-item mr-2">
                                <strong>Category: </strong>
                                <span class="color-text-a">{{post.category}}</span>
                            </li>
                            <li class="list-inline-item">
                                <strong>Date: </strong>
                                <span class="color-text-a">{{post.published_date}}</span>
                            </li>
                        </ul>
                    </div>
                    <div class="post-content color-text-a">
                        <p class="post-intro">
                            {{post.content}}

                        </p>

                        <blockquote class="blockquote">
                            <p class="mb-4">{{post.quote_content}}</p>
                            <footer class="blockquote-footer">
                                <strong>{{post.quote_author}}</strong>
                                <cite title="Source Title">Author</cite>
                            </footer>
                        </blockquote>
                        <p>
                            {{post.quote_content}}
                        </p>
                    </div>
                    <div class="post-footer">
                        <div class="post-share">
                            <span>Share: </span>
                            <ul class="list-inline socials">
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="bi bi-facebook" aria-hidden="true"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="bi bi-twitter" aria-hidden="true"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="bi bi-instagram" aria-hidden="true"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#">
                                        <i class="bi bi-linkedin" aria-hidden="true"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- added field for prev and next !-->
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Prev Post</h5>
                                    <a href="{% url 'blog:blog-single' pid=prev.id %}" class="btn btn-primary">{{prev.title}}{{prev.id}}</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Next Post</h5>
                                    <a href="{% url 'blog:blog-single' pid=next.id %}" class="btn btn-primary">{{next.title}}{{next.id}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br><br>
                    <!-- end prev and next field -->
                </div>
                <div class="col-md-10 offset-md-1 col-lg-10 offset-lg-1">
                    <div class="title-box-d">
                        <h3 class="title-d">Comments (4)</h3>
                    </div>
                    <div class="box-comments">
                        <ul class="list-comments">
                            <li>
                                <div class="comment-avatar">
                                    <img src=" {% static 'assets/img/author-2.jpg' %}" alt="">
                                </div>
                                <div class="comment-details">
                                    <h4 class="comment-author">Emma Stone</h4>
                                    <span>18 Sep 2017</span>
                                    <p class="comment-description">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores reprehenderit, provident cumque ipsam temporibus maiores quae natus libero optio, at qui beatae ducimus placeat debitis voluptates amet corporis.
                                    </p>
                                    <a href="3">Reply</a>
                                </div>
                            </li>
                            <li class="comment-children">
                                <div class="comment-avatar">
                                    <img src=" {% static 'assets/img/author-1.jpg' %}" alt="">
                                </div>
                                <div class="comment-details">
                                    <h4 class="comment-author">Oliver Colmenares</h4>
                                    <span>18 Sep 2017</span>
                                    <p class="comment-description">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores reprehenderit, provident cumque ipsam temporibus maiores quae.
                                    </p>
                                    <a href="3">Reply</a>
                                </div>
                            </li>
                            <li>
                                <div class="comment-avatar">
                                    <img src=" {% static 'assets/img/author-2.jpg' %}" alt="">
                                </div>
                                <div class="comment-details">
                                    <h4 class="comment-author">Emma Stone</h4>
                                    <span>18 Sep 2017</span>
                                    <p class="comment-description">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores reprehenderit, provident cumque ipsam temporibus maiores quae natus libero optio.
                                    </p>
                                    <a href="3">Reply</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="form-comments">
                        <div class="title-box-d">
                            <h3 class="title-d"> Leave a Reply</h3>
                        </div>
                        <form class="form-a">
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <div class="form-group">
                                        <label for="inputName">Enter name</label>
                                        <input type="text" class="form-control form-control-lg form-control-a" id="inputName" placeholder="Name *" required>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <div class="form-group">
                                        <label for="inputEmail1">Enter email</label>
                                        <input type="email" class="form-control form-control-lg form-control-a" id="inputEmail1" placeholder="Email *" required>
                                    </div>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <div class="form-group">
                                        <label for="inputUrl">Enter website</label>
                                        <input type="url" class="form-control form-control-lg form-control-a" id="inputUrl" placeholder="Website">
                                    </div>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <div class="form-group">
                                        <label for="textMessage">Enter message</label>
                                        <textarea id="textMessage" class="form-control" placeholder="Comment *" name="message" cols="45" rows="8" required></textarea>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-a">Send Message</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Blog Single-->

</main>
<!-- End #main -->
{% endblock %}

templates/latest_posts.html
{% load static %}{% load tags %} {% for post in posts %}
<div class="carousel-item-c swiper-slide">
    <div class="card-box-b card-shadow news-box">
        <div class="img-box-b">
            <img src="{% static 'assets/img/post-2.jpg' %}" alt="" class="img-b img-fluid">
        </div>
        <div class="card-overlay">
            <div class="card-header-b">
                <div class="card-category-b">
                    <a href="#" class="category-b">{{post.category}}</a>
                </div>
                <div class="card-title-b">
                    <h2 class="title-2">
                        <a href="{% url 'blog:blog-single' %}">{{post.title}}</a>
                        <br> {{post.about_tittle}}</a>
                    </h2>
                </div>
                <div class="card-date">
                    <span class="date-b">{{ post.published_date|date:'d M Y' }} </span>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}